project:
  type: website

website:
  title: "Jeff Bale"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jeffbale1/JeffBale
      - icon: linkedin
        href: https://www.linkedin.com/in/jeff-bale-41509323/
format:
  html:
    theme: superhero
    css: styles.css

editor: visual

execute:
  freeze: auto
